spring:
  application:
    name: movie-service-common
  profiles:
    # dev / pro
    active: dev
  redis:
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: 1233
    # 连接超时时间（毫秒）
    timeout: 5000
    # 采用默认的lettuce而不是jedis
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0
  zipkin:
    base-url: http://localhost:9000
pagehelper:
  # page helper 方言
  helperDialect: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
